
services:

  contenedores:
    build:  .
    image:  mkdocs-local:contenedores
    container_name: contenedores
    ports:
      - "${PORT:-8000}:8000"
    security_opt: 
      - label=disable
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true


