site_name: Contenedores

# site_description: Documentación y apuntes sobre contenedores
site_description: "Documentacion sobre contenedores de software: Docker, Podman, etc."

site_url: https://alejrot.github.io/contenedores/

# # Repositorio
# repo_url: https://github.com/alejrot/contenedores
# repo_name: contenedores
# edit_uri: edit/master/docs/



theme: 
  name: material
  # favicon: images/favicon.png   # no anda
  icon:
    #icono de pagina
    logo: simple/markdown  
    # logo: bootstrap/activity  # icono local 
    # iconos de avance y retroceso 
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    # Icono de repositorio
    repo: fontawesome/brands/github
    tag:
      # icono comodín
      # default: material/cursor-default-click
      # iconos especificos
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
      yaml: simple/yaml
      python: fontawesome/brands/python
      docker: fontawesome/brands/docker
      podman: simple/podman
      markdown: fontawesome/brands/markdown
      mkdocs: simple/materialformkdocs
      ts: simple/typescript
      csv: fontawesome/solid/file-csv
      bash: simple/gnubash
      express: simple/express
      reactjs: simple/react
      nodejs: fontawesome/brands/node-js
      npm:  material/npm
      pnpm: simple/pnpm
      vitejs: simple/vite
      sqlite: simple/sqlite
      sqlalchemy: simple/sqlalchemy
      mysql: simple/mysql
      postgresql: simple/postgresql
      mariadb: simple/mariadb
      # mariadb: simple/mariadbfoundation
      mongodb:  simple/mongodb
      k8s:      simple/kubernetes
 
  features:
    # codigo y pestañas
    - content.tabs.link         # pestañas sincronizadas
    - content.code.copy         # botón de copia 
    - content.code.annotate     # botones de anotaciones emergentes
    # opciones de búsqueda
    - search.suggest      # sugerencias en caja de búsqueda
    - search.highlight  # remarcado en página
    - search.share      # link 'compartir' en caja de búsqueda
    # - search.exclude
    # opciones de navegación
    - navigation.instant
    - navigation.instant.progress   # progreso de carga (conexiones lentas)
    - navigation.tracking
    # pestañas de contenido
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    # - navigation.prune 
    # - navigation.indexes 
    - toc.follow
    # - toc.integrate   # integra indice derecho (secciones) adentro del izquierdo (rutas)
    - navigation.top  # boton emergente para volver al inicio  - aparece al intentar subir con el scroll

    # Pie de pagina
    - navigation.footer

    # header y anuncios
    - header.autohide
    - announce.dismiss

    # acciones sobre repositorio
    # - content.action.edit
    # - content.action.view


  # soporte de idiomas
  language: es    # Idioma predefinido
  # direction: ltr


  # Opciones de temas y colores
  palette: 
    # Cambio de paleta al modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb 
        name: Cambia al modo oscuro 
      # primary: indigo
      # accent: blue
      primary: red
      accent: orange
    # Cambio de paleta al modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline    
        name: Cambia al modo claro      # mensaje
      primary: red
      accent: orange

markdown_extensions: 
  # "advertencias"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # anotaciones
  - attr_list
  - md_in_html
  - pymdownx.superfences
  # grids
  - attr_list
  - md_in_html
  # emojis - iconos
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      # Iconos LOCALES
      # options:
      #   custom_icons:
      #     - overrides/.icons    # Carpeta local - ruta desde directorio raiz del proyecto
  # pestañas de contenido
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # matematica
  - pymdownx.arithmatex:
      generic: true
  # Tablas (activado por defecto)
  - tables
  #bloques codigo
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite   # habilita remarcado de renglones
  - pymdownx.snippets       # habilita importar código de otros archivos
  - pymdownx.superfences    # habilita anidado de otros contenidos
  # notas al pie
  - footnotes
  # formateo
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde




plugins:
  # lectura tablas desde archivo
  # - search
  # - table-reader
  # privacidad - hace copia local de contenidos remotos
  - privacy
  # busqueda
  - search

  # etiquetas
  - tags:
      tags_file: tags.md


  # habilitacion por grupo 
  # grupo Nº1: servidor remoto ('Continuous Integration')
  - group:
      enabled: !ENV CI
      plugins:
        # fechas de repositorio
        - git-revision-date-localized:
            enabled: true
            enable_creation_date: true
            type: date        # fecha
            # type: datetime    # fecha y hora
            # type: iso_date    # fecha ISO (sólo numeros)
            # type: iso_datetime  # fecha ISO (sólo numeros)
            # type: timeago       # tiempo desde publicación
            fallback_to_build_date: true
        # Tarjetas PNG automáticas 
        - social:
            cards_layout: default/accent



extra:
#   homepage: https://alejrot.github.io/contenedores/

  # Etiquetas de contenidos
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    YAML: yaml
    Python: python
    Docker: docker 
    Podman: podman 
    MarkDown: markdown
    MkDocs: mkdocs
    TypeScript: ts
    CSV: csv
    Bash: bash 
    Express: express
    ReactJS: reactjs
    NodeJS: nodejs
    NPM: npm
    PNPM: pnpm
    ViteJS: vitejs
    SQLite: sqlite
    SQLAlchemy:  sqlalchemy
    MySQL:  mysql
    PostgreSQL:  postgresql
    MariaDB: mariadb
    MongoDB: mongodb
    Kubernetes: k8s


nav:
  - Introducción: index.md
  - Docker & Podman:
    - Introducción:               docker/01_intro.md
    - Virtualización:             docker/02_virtualizacion.md
    - Escritorio:                 docker/03_desktop.md
    - Imágenes:                   docker/04_imagenes.md
    - Contenedores:               docker/05_contenedores.md
    - Puertos:                    docker/08_puertos.md
    - Comando Run:                docker/09_run.md
    - Logs:                       docker/06_logs.md
    - Variables de Entorno:       docker/07_variables_entorno.md
    - Redes Bridge:               docker/10_redes.md
    - Volumenes:                  docker/13_volumes.md
    - Inspeccionar metadatos:     docker/14_inspect.md

    - Pods (podman):    podman/pods.md

  - Archivo Dockerfile:
    - Dockerfile:                 docker/11_dockerfile.md

  - Archivo Compose:
    - Docker Compose:     docker/12_compose.md


  - Kubernetes:
    - Introducción:     k8s/intro.md
    - Kubectl y complementos:      k8s/cliente.md
    - Manifiesto:       k8s/manifiesto.md
    - Servicios:        k8s/servicios.md
    - Deployment:       k8s/deployment.md
    - DaemonSet:        k8s/daemonset.md
    - StatefulSet:      k8s/statefulet.md
    - Ingress:          k8s/ingress.md
    - ConfigMap:        k8s/configmap.md
    - Secrets:          k8s/secrets.md
    - Kustomization:    k8s/kustomization.md

  - Tags: tags.md





